### ISSUE TITLE
Ordered factor as frame aesthetic gives error

### ISSUE THREAD

**Issue by yeedle** [thomasp85/gganimate#16] opened 2016-08-30 21:55 UTC
When using an ordered factor as a frame aesthetic I get an error. When I remove the `ordered = T` argument, it works without any errors.

Here's reproducible code. 

```
months  <- factor( c("Jan", "Apr", "Jul", "Oct"),
     levels = c("Jan",  "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"),
     ordered = TRUE)
df <- data.frame(x = 1:4, y = 1:4 , m = months)
plot <- ggplot(df, aes(x, y, frame = m))
gg_animate(plot)
```

output:

```
Error in frame_vec == f : comparison of these types is not implemented
In addition: Warning message:
Incompatible methods ("Ops.ordered", "Ops.factor") for "==" 
```

Here's my session info in case it's something on my end:

```
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_2.1.0 gganimate_0.1

loaded via a namespace (and not attached):
 [1] labeling_0.3     colorspace_1.2-6 scales_0.4.0     plyr_1.8.4       rsconnect_0.4.3 
 [6] htmltools_0.3.5  tools_3.3.1      base64enc_0.1-3  withr_1.0.2      animation_2.4   
[11] gtable_0.2.0     Rcpp_0.12.5      grid_3.3.1       digest_0.6.9     munsell_0.4.3 
```

**Comment by ryancbriggs** [comment] 2018-05-27 01:36
I have a related issue, which is that when using `cumulative = TRUE` and a factor for a frame I get an error. My issue (and the above issue) are resolved by placing the factor inside `as.numeric().` Here is code to reproduce my issue:

```
library("ggplot2")
library("gganimate")

letters  <- factor(c("a", "b", "c", "d"))
df <- data.frame(x = 1:4, y = 1:4 , l = letters)

fails <- ggplot(df, aes(x, y, frame = l, cumulative = TRUE))+ 
  geom_point()
gganimate(fails)

works <- ggplot(df, aes(x, y, frame = as.numeric(l), cumulative = TRUE)) + 
  geom_point()
gganimate(works)
```

**Comment by dgrtwo** [comment] 2018-07-05 19:48
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)

**Closed as completed by dgrtwo** 2018-07-05 19:48 UTC
