### ISSUE TITLE
Transition_reveal for both points and geom_smooth

### ISSUE THREAD

**Issue by Janzeero** [thomasp85/gganimate#209] opened 2018-11-07 19:43 UTC
Here is a [data](https://drive.google.com/file/d/1KxADCgv-VsQsNuwW94KgiwP8b11x8adG/view). I can make through transition_reveal appearing geom_points. Looks nice, but I also wanna add exponential regression and visualise both simultaneously. Transition_reveal makes render neither with both smooth and points, nor with just smooth. Its possible only for geom_points. Whats wrong?
[Gif only with geom_point](https://i.stack.imgur.com/bP0kt.gif)
[Static with both point and line](https://i.stack.imgur.com/bqU8l.png)

Here is a code and error. Should be exponential visualisation of decomposition process of tree wood, where t - age of sampling, Pt - its density.
`gif<-ggplot(data, aes(t,Pt))+geom_point(shape=21, aes(fill=group),col="black",size=3)+stat_smooth(method="nls", data=decay, method.args = list(formula = y~a*exp(-b*x), start = list(a=570,b=2*log(2)/570)), se=F,size=0.5, col="black",linetype="dotted")+transition_reveal(Pt,t)`
Error:
`Error in `[.data.frame`(df, , c("alpha", "colour", "size", "linetype")) : undefined columns are chosen`

Thank you a lot for any suggestion and attention!

**Comment by Janzeero** [comment] 2018-11-08 12:28
Column `group` is missing, lts made like `data$group<-with(data, ifelse(Pt<100,0,ifelse(Pt<200,1,ifelse(Pt<300,2,ifelse(Pt<400,3,ifelse(Pt<500,4,5)))))`

**Comment by ptoche** [comment] 2018-11-30 12:50
Edit your first post above with a ``reprex`` and remove the second comment for clarity.

https://reprex.tidyverse.org/

**Comment by MichaelChirico** [comment] 2018-12-09 08:09
I think this is similar to something I'm trying to accomplish now:

```
library(ggplot2)
library(gganimate)
library(data.table)

DT = data.table(
  grp = sample(4L, 1e3, TRUE)
)
DT[ , v := rnorm(.N, sd = 1/.BY$grp), by = grp]
DT[ , grpI := seq_len(.N), by = grp]
```

Static plot = final frame of animation:

```
ggplot(DT, aes(grp, v)) + geom_jitter(width = .2)
```

<img width="1190" alt="screen shot 2018-12-09 at 3 55 03 pm" src="https://user-images.githubusercontent.com/7606389/49694744-d6c4fe00-fbca-11e8-9b04-5a130563aa55.png">

Attempt (doesn't work) in `gganimate`:

```
ggplot(DT, aes(grp, v)) + 
  geom_jitter(width = .2) + 
  transition_reveal(grp, grpI)
```

![fail_example](https://user-images.githubusercontent.com/7606389/49694827-67e8a480-fbcc-11e8-8b4c-3dc6d9506c11.gif)

I think it's failing because `?transition_reveal` suggests it only works for polygons/lines at the moment.

I think this is a nice animation for showing how points can accumulate to make a distribution.

Here's a workaround that's quite slow to render since it quadratically explodes the number of rows in the input:

```
ggplot(DT[DT, .(i.grpI, x.grp, x.v), 
          on = .(grpI <= grpI, grp == grp), allow.cartesian = TRUE], 
       aes(x.grp, x.v)) + 
  geom_jitter(width = .2) + 
  transition_states(
    i.grpI,
    transition_length = 1,
    state_length = 2
  )
```

![success_example](https://user-images.githubusercontent.com/7606389/49694846-c9a90e80-fbcc-11e8-8c8c-00866ae4fbb5.gif)

**Comment by thomasp85** [comment] 2018-12-09 08:53
I think you should be able to accomplish what you want by giving a unique group aesthetic to each point

**Comment by MichaelChirico** [comment] 2018-12-09 09:14
Thanks @thomasp85. Could you elaborate? I'm also new to most things `ggplot2` as well...

**Comment by thomasp85** [comment] 2018-12-09 10:34
All geoms have a group aesthetic even though it is unused by many. gganimate used it though, in order to figure out which graphic elements are part of the same “entity”.

If you do `geom_jitter(aes(group=seq_len(x.v)), width = .2)` I think you’d get what you want

**Comment by MichaelChirico** [comment] 2018-12-09 12:54
(assume you mean `seq_along`)

Hmm, not sure I follow.

These both look the same as above to me:

```
ggplot(DT, aes(grp, v)) + 
  geom_jitter(aes(group = seq_along(v)), width = .2) + 
  transition_reveal(grp, grpI)
```

```
ggplot(DT[DT, .(i.grpI, x.grp, x.v), 
          on = .(grpI <= grpI, grp == grp), allow.cartesian = TRUE], 
       aes(x.grp, x.v)) + 
  geom_jitter(aes(group=seq_along(x.v)), width = .2) + 
  transition_states(
    i.grpI,
    transition_length = 1,
    state_length = 2
  )
```

Anyway, I'm ~basically fine with how the second one looks (constructing the full "scatter boxplot" gradually), the problem is that it's a bit awkward to create the data to mimic the `transition_reveal` animation (imperfectly at that, since `jitter` is re-applied for each `grpI`).

My aim is to make the first one use `transition_reveal` to more naturally/concisely evoke the same behavior

**Comment by Janzeero** [comment] 2018-12-10 07:32
Thanks, I have already got that through this code
` %>% 
  mutate(gr=factor(case_when(Pt<200 ~ 1,
                             Pt<300 ~ 2,
                             Pt<400 ~ 3,
                             Pt<500 ~ 4, 
                             TRUE ~ 5))) %>% 
  arrange(t) %>% 
  rowid_to_column() %>% # arrange and add rowid for the transition_reveal
  mutate(predict=predict(loess(Pt ~ t, data=.), .)) %>% # calculate the predicted values
  mutate(predict_lag=lag(predict,default = max(predict)), # add the next values for segments
         t_lag=lag(t,default = min(t))) %>% 
  ggplot(aes(t,Pt)) + 
  geom_point(aes(fill=gr),
             shape=21,col="black",
             size=3, show.legend = F) + 
   geom_segment(aes(x=t, y=predict, xend=t_lag, yend=predict_lag),
                col="black",linetype="dotted") +
   transition_reveal(rowid, rowid)`
Using exponential code instead of loess function.

**Comment by thomasp85** [comment] 2018-12-10 07:46
@MichaelChirico can you provide a reproducible example... the code you have given produces an error as `grpI` does not exist

**Comment by MichaelChirico** [comment] 2018-12-10 07:53
@thomasp85 sorry, bad copy-pasting... included in original post [here](https://github.com/thomasp85/gganimate/issues/209#issuecomment-445518813)

**Comment by thomasp85** [comment] 2018-12-10 07:58
hmm... I can see that adding a unique group doesn't really alter the output, though it should... I'll look into it

**Comment by Janzeero** [comment] 2018-12-10 08:02
Sorry, I am not so good in writing examples :(
data is called `decay`
`decaying_plot <- ggplot(decay, aes(t,Pt)) + 
  geom_point(shape=21, aes(fill=group),col="black",size=3) + 
  stat_smooth(method="nls", data=decay, 
              method.args = list(formula = y~a*exp(-b*x), 
                                 start = list(a=570,b=2*log(2)/570)), 
              se=F,size=0.5, 
              col="black",linetype="dotted")+xlab("Вік зразка, років")+ylab("Щільність зразка, кг/м3")+theme(legend.position="none")`

`decay %>% 
  mutate(gr=factor(case_when(Pt<200 ~ 1,
                             Pt<300 ~ 2,
                             Pt<400 ~ 3,
                             Pt<500 ~ 4, 
                             TRUE ~ 5))) %>% 
  arrange(t) %>% 
  rowid_to_column()%>%`

`mutate(predict=predict(nls(Pt ~ a*exp(-b*t),start = list(a=570,b=2*log(2)/570), data=.), .)) %>% 
  mutate(predict_lag=lag(predict,default = max(predict)), 
         t_lag=lag(t,default = min(t))) %>% 
  ggplot(aes(t,Pt)) + 
  geom_point(aes(fill=gr),
             shape=21,col="black",
             size=3, show.legend = F) + 
  geom_segment(aes(x=t, y=predict, xend=t_lag, yend=predict_lag),
               col="black",linetype="dotted") +
  transition_reveal(rowid, rowid)`

So I get something like [this](https://drive.google.com/open?id=14jidNoVUD50zfDqqhsioJyAQseOH8m6w)

**Comment by thomasp85** [comment] 2018-12-10 08:02
Ah... I'm messing up my head because I'm currently doing some last minute changes to the transition api's... Setting `group` will work in the future, but for now you should do `transition_reveal(seq_along(grp), grpI)`

**Comment by thomasp85** [comment] 2018-12-10 08:03
![image](https://user-images.githubusercontent.com/1775316/49718480-7ed5d800-fc5a-11e8-9156-30064492a21d.png)

**Comment by ptoche** [comment] 2018-12-10 08:08
reprex below

``` r
library(reprex)

library(ggplot2)
library(gganimate)
library(data.table)

DT = data.table(
  grp = sample(4L, 1e3, TRUE)
)
DT[ , v := rnorm(.N, sd = 1/.BY$grp), by = grp]
DT[ , grpI := seq_len(.N), by = grp]


# Example 1
ggplot(DT, aes(grp, v)) + 
  geom_jitter(aes(group = seq_along(v)), width = .2) + 
  transition_reveal(grp, grpI)

# Example 2
ggplot(DT[DT, .(i.grpI, x.grp, x.v), 
          on = .(grpI <= grpI, grp == grp), allow.cartesian = TRUE], 
       aes(x.grp, x.v)) + 
  geom_jitter(aes(group=seq_along(x.v)), width = .2) + 
  transition_states(
    i.grpI,
    transition_length = 1,
    state_length = 2
  )
```

![](https://i.imgur.com/tuyC8BV.gif)

Created on 2018-12-10 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by Janzeero** [comment] 2018-12-10 08:17
thanks, looking good!

**Comment by thomasp85** [comment] 2018-12-10 08:18
```r
ggplot(DT, aes(grp, v)) + 
  geom_jitter(width = .2) + 
  transition_reveal(seq_along(grp), grpI)
```
![reveal_points](https://user-images.githubusercontent.com/1775316/49719148-9b730f80-fc5c-11e8-9d3d-05dd83a09a37.gif)

**Comment by MichaelChirico** [comment] 2018-12-10 09:47
@thomasp85 looking exactly like I envisioned! love it! excellent!

**Comment by thomasp85** [comment] 2018-12-10 09:49
@MichaelChirico be aware that I will soon deprecate the `id` argument in all transitions and wholeheartedly embrace the use of the `group` aesthetic (should have done this from the beginning - don't know what happened), so you'll have to adjust this to the first proposed solution

**Comment by thomasp85** [comment] 2018-12-10 09:57
@Janzeero your issue is entangled in a lot of stuff that I'm working on right now - a fix will be provided soon

**Comment by thomasp85** [comment] 2018-12-10 10:58
@Janzeero just to be sure - Is this the result you are after?
![reveal_points](https://user-images.githubusercontent.com/1775316/49728400-f0ba1b80-fc72-11e8-86c5-71ed84b247db.gif)

**Comment by thomasp85** [comment] 2018-12-10 11:00
@MichaelChirico the changes I talked about has been merged and you should now do:

```r
ggplot(DT, aes(grp, v, group = seq_along(v))) + 
  geom_jitter(width = .2) + 
  transition_reveal(grpI)
```

to get the correct result

**Comment by fmmattioni** [comment] 2019-02-07 13:31
I would be curious to know how this was produced with the new API. There are some tutorials online, but they all use the deprecated `gganimate()`.

> @Janzeero just to be sure - Is this the result you are after?
> ![reveal_points](https://user-images.githubusercontent.com/1775316/49728400-f0ba1b80-fc72-11e8-86c5-71ed84b247db.gif)

**Comment by jlopezper** [comment] 2019-04-09 22:14
I join the request of @fmmattioni. @thomasp85 could you please provide an example of how to make that last plot? I just also found examples with deprecated API like [this](http://varianceexplained.org/files/loess.html).

**Comment by thomasp85** [comment] 2019-04-10 06:51
My last response includes the code

**Comment by jlopezper** [comment] 2019-04-10 07:18
Ok, sorry, I didn't get it! Thanks!

**Comment by johannesbjork** [comment] 2019-05-20 19:34
> My last response includes the code

Where exactly? I only see the code for the scatter plot... Thanks!

**Comment by jhelvy** [comment] 2021-03-02 17:28
> > My last response includes the code
> 
> Where exactly? I only see the code for the scatter plot... Thanks!

I also am not seeing any code to produce the animated points + smooth chart.

When I run this code, I get the following error: 

```r
ggplot(mtcars, aes(x = mpg, y = hp)) +
    geom_point() +
    geom_smooth(method = 'loess', formula = 'y ~ x', se = FALSE) +
    transition_reveal(mpg)
```

```
Error in `$<-.data.frame`(`*tmp*`, "group", value = "") : 
  replacement has 1 row, data has 0
```

**Closed as completed** 2021-03-18 14:38 UTC
