### ISSUE TITLE
Green frames after animate()

### ISSUE THREAD

**Issue by gudryan** [thomasp85/gganimate#432] opened 2021-03-14 14:19 UTC
I am running:

library(gapminder)
head(gapminder)

p <- ggplot(
  gapminder, 
  aes(x = gdpPercap, y=lifeExp, size = pop, colour = country)
) +
  geom_point(show.legend = FALSE, alpha = 0.7) +
  scale_color_viridis_d() +
  scale_size(range = c(2, 12)) +
  scale_x_log10() +
  labs(x = "GDP per capita", y = "Life expectancy")
p

my.animation<- p + transition_time(year) +
  labs(title = "Year: {frame_time}")

and the output is: 

![Example](https://user-images.githubusercontent.com/10096815/111071924-2b950480-84b7-11eb-9038-603e1c7364fa.gif)

**Comment by thomasp85** [comment] 2021-03-15 07:21
This is a duplicate of #431

It seems to be an issue with the new gifski version and not something that can be solved in gganimate

**Closed as completed by thomasp85** 2021-03-15 07:21 UTC

**Comment by jeroen** [comment] 2021-03-23 08:52
Sorry about this, fixed now in gifski 1.4.3 on CRAN.

**Comment by gudryan** [comment] 2021-03-23 10:42
thank you @jeroen
