### ISSUE TITLE
Parallel execution for speed?

### ISSUE THREAD

**Issue by noamross** [thomasp85/gganimate#23] opened 2016-12-05 19:44 UTC
Creating all of the frames for an animation can take a while.  Perhaps there could be an option to use parallel execution to generate the frame if `option("mc.cores")` is set?

**Comment by noamross** [comment] 2016-12-05 20:10
Realized this is something for the **animation** package.

**Comment by noamross** [comment] 2016-12-05 21:44
Wait, I was wrong, this is something to do here.  I'll take a crack at a PR soon.

**Comment by noamross** [comment] 2016-12-06 20:46
This looks like it would entail a major overhaul, but it would have advantages:

-  Build in use of **magick** rather than **animation** - better portability and dependency management
-  Enable progress bars (even in the parallel case)

Would you accept such a PR?

**Comment by dgrtwo** [comment] 2016-12-07 01:59
This is an awesome idea! Actually I have been recently rewriting a lot of how gganimate works, especially that it now generates the background only once (see [save_gganimate_custom](R/saving.R#L91) in the newest commit), and it does involve using ImageMagick rather than the animation package. (The problem is that the magick package doesn't seem to have support for doing the "dispose" operation I need where we keep a background and iterate over it).

I won't be coding on this for a while so you have my enthusiastic support to jump in there and try adding parallelization etc (just please make sure you're working off of this latest commit!)

**Comment by noamross** [comment] 2016-12-09 14:11
FYI I've opted to put some effort into some PRs for magick first, to
support the dispose options you'll need as well as fast in-memory image
capture so there's no round-trip to disk. More to come!

**Comment by dgrtwo** [comment] 2018-07-05 19:49
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)

**Closed as completed by dgrtwo** 2018-07-05 19:49 UTC
