### ISSUE TITLE
Error in data.frame(..., check.names = FALSE) :    arguments imply differing number of rows:

### ISSUE THREAD

**Issue by JuanGaleano** [thomasp85/gganimate#428] opened 2021-02-11 11:46 UTC
Hello, 

I'm trying to create a animated bar plot, but receiving the message: Error in data.frame(..., check.names = FALSE) :    arguments imply differing number of rows:

The following is an extract of my data frame. The complete df has 7 regions and 52 Semanines per Region, so 364 rows.

Region | Semaine | week            | E_0_men
1          | 1             | 30/12/2019 | 81.86
1          | 2             | 06/01/2020 | 82.61
1          | 3             | 13/01/2020 | 80.54
1          | 4             | 20/01/2020 | 81.27
1          | 5             | 27/01/2020 | 80.72
1          | 6             | 03/02/2020 | 80.30
1          | 7             | 10/02/2020 | 81.74
1          | 8             | 17/02/2020 | 82.07
1          | 9             | 24/02/2020 | 81.97
1          | 10           | 02/03/2020 | 81.04

Everything works if I use Semaine 1 to 50, but I get the error message when using 51 Semaines. I think there is nothing wrong in mi data, as if I take Semaine 1 to 48 and 51 to 52, everything works, but of course I want to get the animated plor for weeks 1 to 52. There is any sort of limitation on 50 points in time? 

Thanks in advance.

**Comment by thomasp85** [comment] 2021-03-11 12:08
Can I get you to post a reprex? If you are unfamiliar with the concept of reprex, please see this page https://reprex.tidyverse.org

**Comment by DasHammett** [comment] 2022-01-01 17:34
I do also have the same error. Please find below code to reproduce (I don't have pandoc installed in this machine, and reprex crashes, but the code should reproduce the error).
```
df <- read.csv(url('https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv'))

df_world <- df %>%
  filter(location == "World") %>%
  select(date, location, new_cases, total_cases, new_deaths, total_deaths)

plot_animated <- df_world %>%
  ggplot(aes(x = date,
             y = new_deaths,
             fill = "orange")) +
  geom_col() +
  guides(fill = "none") +
  scale_y_continuous(labels = scales::comma) +
  labs( x= "",
        y= " ",
        title = "Deaths by COVID-19 \n(Daily change)",
        subtitle = "Date : {closest_state}",
        caption =  "Source: https://covid.ourworldindata.org") +
  transition_states(date, wrap = FALSE) +
  shadow_mark() +
  enter_appear() +
  enter_grow() +
  enter_fade() +
  view_follow(fixed_x = TRUE)

animate(plot_animated, nframes= 400, width = 1000, height= 600, fps = 7)
```
When you run the animate function, the error happens:
```
Error in data.frame(..., check.names = FALSE) :
  arguments imply differing number of rows: 1419, 400
```

**Comment by ablack3** [comment] 2022-04-05 14:10
Same error for me.

**Comment by thomasp85** [comment] 2023-09-07 09:18
Seems to be fixed in dev

**Closed as completed by thomasp85** 2023-09-07 09:18 UTC
Labels: bug, reprex
