### ISSUE TITLE
Installation fails on ubuntu

### ISSUE THREAD

**Issue by niklasvm** [thomasp85/gganimate#105] opened 2018-07-20 08:39 UTC
Good day

I am quite eager to try out gganimate however when trying to install on ubuntu the dependency patchwork fails install.

```
> devtools::install_github('thomasp85/gganimate')
Downloading GitHub repo thomasp85/gganimate@master
from URL https://api.github.com/repos/thomasp85/gganimate/zipball/master
Installing gganimate
Downloading GitHub repo thomasp85/patchwork@master
from URL https://api.github.com/repos/thomasp85/patchwork/zipball/master
Installing patchwork
'/usr/local/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpqCX5Jt/devtools2963337973b9/thomasp85-patchwork-7fb35b1'  \
  --library='/home/rstudio/xxxxxxxxxxxxxxxx/packrat/lib/x86_64-pc-linux-gnu/3.4.4' --install-tests 

Installation failed: Command failed (1)
'/usr/local/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpqCX5Jt/devtools296330087b33/thomasp85-gganimate-13a9a29'  \
  --library='/home/rstudio/xxxxxxxxxxxxxxxx/packrat/lib/x86_64-pc-linux-gnu/3.4.4' --install-tests 

Installation failed: Command failed (1)
```
Any advice or solution? I see the build is failing at https://github.com/thomasp85/patchwork

**Comment by thomasp85** [comment] 2018-07-20 19:11
The failed build on appveyor is a Windows/Appveyor issue. I don’t know why patchwork fails on your system — can you try to install it directly and report back what it says?

**Comment by niklasvm** [comment] 2018-07-21 17:18
I have tried installing just patchwork and it fails with the same non-specific error: command failed
```{r}
> devtools::install_github("thomasp85/patchwork")
Downloading GitHub repo thomasp85/patchwork@master
from URL https://api.github.com/repos/thomasp85/patchwork/zipball/master
Installing patchwork
'/usr/local/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL '/tmp/RtmpGatQG2/devtools5631d67d481/thomasp85-patchwork-7fb35b1'  \
  --library='/usr/local/lib/R/site-library' --install-tests 

Installation failed: Command failed (1)
```

**Comment by thomasp85** [comment] 2018-07-23 08:42
I'm sorry that I can't be of help here. As I can't reproduce the installation problems I can't really fix it. Closing as this is really a patchwork issue - you're welcome to repost in the patchwork issues, but the same caveats about being able to reproduce it still applies

**Closed as completed by thomasp85** 2018-07-23 08:42 UTC
